### ISSUE TITLE
Usb: host: pad and midi host

### ISSUE THREAD

**Issue by jhusak** [raspberrypi/tinyusb#11]
I kindly ask to add usb host support for game controllers and midi. There is a big niche in retrogaming and retrocomputing, so is in midi branch.

There is much more fun to connect such devices, than ordinary mouse or keyboard.
Thanks in advance.

**Comment by lurch** [comment]
At some point (soon?) we'll be switching to use upstream tinyusb (see https://github.com/raspberrypi/pico-sdk/pull/321 ), so I doubt we'll be adding any "new features" in this repo, and any requests probably need to be made upstream? https://github.com/hathach/tinyusb

**Comment by jhusak** [comment]
Sure. Thank you for answer.
