### ISSUE TITLE
README hints

### ISSUE THREAD

**Issue by Tails86** [raspberrypi/tinyusb#2]
Thanks to everyone who put in the effort to make TinyUSB compatible with pico!

The first thing that tripped me up was looking through the README and not seeing any mention of support for pico. Would you be able to at least say that pico is supported there? Linking to your usb example from with tinyusb/docs/boards.md would help too. Thanks!

**Comment by lurch** [comment]
This is already fixed upstream, which is probably where it matters? :slightly_smiling_face: 
https://github.com/hathach/tinyusb
