### ISSUE TITLE
USB queue FIFO overflows.

### ISSUE THREAD

**Issue by ndinsmore** [raspberrypi/tinyusb#5]
**Describe the bug**
Without the following PR which has been merged into the upstream repo,  the queue FIFO **will overflow**  because it relies on a rollover mechanism that doesn't work.
 https://github.com/hathach/tinyusb/pull/655

**To reproduce**
Any USB example is doing it.  I actually don't know how the examples appear to work without this.

**Comment by lurch** [comment]
Can this be closed, now that we're using an updated TinyUSB?
